version: "3.3"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/script.js:/usr/share/nginx/html/script.js:ro
      - ./nginx/classless.css:/usr/share/nginx/html/classless.css:ro

  fastapi:
    build: ./fastapi
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/mydb
    ports:
      - "8000:8000"

volumes:
  pgdata:
